/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function build_tree(a: number): number;
export function flatten_tree(a: number): number;
export function greet(a: number, b: number): void;
export function __wbg_list_free(a: number): void;
export function list_show(): number;
export function list_create(a: number): void;
export function list_update(a: number): void;
export function list_delete(a: number): void;
export function __wbg_todo_free(a: number): void;
export function todo_new(a: number, b: number, c: number, d: number): number;
export function todo_id(a: number, b: number): void;
export function todo_set_id(a: number, b: number, c: number): void;
export function todo_text(a: number, b: number): void;
export function todo_set_text(a: number, b: number, c: number): void;
export function finder_flatten_tree(a: number): number;
export function main(): void;
export function __wbg_universe_free(a: number): void;
export function universe_tick(a: number): void;
export function universe_new(): number;
export function universe_render(a: number, b: number): void;
export function finder_build_tree(a: number): number;
export function __wbg_wasmmarkdowneditor_free(a: number): void;
export function wasmmarkdowneditor_main(): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_start(): void;
