name: Continuous Integration

on: [push, pull_request]

jobs:
  tsc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/yarn-cache
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: tsc
        run: yarn tsc

  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/yarn-cache
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: lint
        run: yarn lint

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/yarn-cache
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: test
        run: yarn test

  e2e:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/yarn-cache
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run E2E Test
        run: yarn concurrently 'yarn storybook' 'yarn cy:sb:run' -k -s first
      - name: workaround for detached HEAD
        run: |
          git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull || true
      - name: run reg-suit
        run: |
          yarn reg-suit run -c regconfig.e2e.json

  vrt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ./.github/actions/yarn-cache
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: install JP font
        run: |
          sudo apt-get install fonts-ipafont
      - name: run storycap
        run: |
          yarn storycap http://localhost:9009 --serverCmd "yarn start-storybook -p 9009" --serverTimeout 3000000
      - name: workaround for detached HEAD
        run: |
          git checkout ${GITHUB_REF#refs/heads/} || git checkout -b ${GITHUB_REF#refs/heads/} && git pull || true
      - name: run reg-suit
        run: |
          yarn reg-suit run

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
