# TODO: refactor
name: storybook deploy on comment

on:
  issue_comment:
    types: [created]

jobs:
  deploy-storybook-on-comment:
    if: "contains(github.event.comment.body, 'deploy-storybook') && github.event.issue.pull_request"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache pnpm
        uses: suimenkathemove/pnpm-cache-action@v1.0.0
      - name: Install dependencies
        run: pnpm install
      - name: Build Storybook
        run: pnpm build-storybook
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Upload to S3
        run: |
          aws s3 sync ./storybook-static s3://$S3_BUCKET_NAME/pr-$GITHUB_PULL_REQUEST_ID --quiet
      - name: Comment URL
        run: |
          curl -X POST -H "Authorization: token ${GITHUB_TOKEN}" -i ${GITHUB_PULL_REQUEST_URL} -d "`printf '{\"body\":\"deploy to %s\"}' ${S3_URL}/"pr-"${GITHUB_PULL_REQUEST_ID}`"

env:
  S3_URL: http://react-sandbox-storybook.s3-website-ap-northeast-1.amazonaws.com
  S3_BUCKET_NAME: react-sandbox-storybook
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_PULL_REQUEST_ID: ${{ github.event.issue.number }}
  GITHUB_PULL_REQUEST_URL: ${{ github.event.issue.pull_request.url }}
